BluegrassPetCare/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using BluegrassPetCare.Data;
using BluegrassPetCare.Models;
using BluegrassPetCare.Models.PetViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BluegrassPetCare.Controllers
{
    public class PetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public PetsController(ApplicationDbContext ctx, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _context = ctx;
        }


        // GET: Pets
        public async Task<ActionResult> Index(string searchString, string petSearchString)
        {

            var user = await GetCurrentUserAsync();


            if (user.IsVeterinarian == false)
            {
                var userPets = await _context.Pet
                        .Include(p => p.Breed)
                        .Include(p => p.Sex)
                        .Include(p => p.Species)
                        .Include(p => p.Notes)
                        .Where(p => p.UserId == user.Id)
                        .ToListAsync();
                return View(userPets);
            }
            else if (user.IsVeterinarian == true)
            {
                var userPets = await _context.Pet
                            .Include(p => p.Breed)
                            .Include(p => p.Sex)
                            .Include(p => p.Species)
                            .Include(p => p.Notes)
                            .Include(p => p.User)
                            .ToListAsync();
                return View(userPets);
            }


            else if (searchString != null)
            {
                var pet = await _context.Pet.Where(p => p.UserId == user.Id)
                    .Where(p => p.Name.Contains(searchString))
                    .Include(p => p.Breed)
                    .Include(p => p.Sex)
                    .Include(p => p.Species)
                    .Include(p => p.Notes)
                    .ToListAsync();

                return View(pet);
            }
            else
                {
               

                var pet = await _context.Pet.Where(p => p.UserId == user.Id)
                    .Include(p => p.Breed)
                    .Include(p => p.Sex)
                    .Include(p => p.Species)
                    .Include(p => p.Notes)
                .ToListAsync();
                return View(pet);

                
            }
            
        }
            

            // GET: Pets/Details/5
            public async Task<ActionResult> Details(int id)
        {
            var pet = await _context.Pet
                .Include(p => p.Breed)
                .Include(p => p.Sex)
                .Include(p => p.Species)
                .Include(p => p.Notes)
                  .ThenInclude(u => u.User )
                .Include(p => p.User)
                .FirstOrDefaultAsync(p => p.PetId == id);

            var viewModel = new PetDetailViewModel()
            {
                Pet = new Pet()
            };

            viewModel.Pet.PetId = pet.PetId;
            viewModel.Pet.UserId = pet.UserId;
            viewModel.User = pet.User;
            viewModel.Pet.Name = pet.Name;
            viewModel.Pet.Color = pet.Color;
            viewModel.Pet.ImagePath = pet.ImagePath;
            viewModel.Pet.Birthday = pet.Birthday;
            viewModel.Breed = pet.Breed;
            viewModel.Sex = pet.Sex;
            viewModel.Species = pet.Species;
            viewModel.Pet.Notes = pet.Notes;
            viewModel.Pet.CurrentMedications = pet.CurrentMedications;
            viewModel.Pet.OngoingProblems = pet.OngoingProblems;
            viewModel.Pet.IsSpayedOrNeutered = pet.IsSpayedOrNeutered;



            return View(viewModel);
        }

        // GET: Pets/Create
        public async Task<ActionResult> CreateAsync()
        {
            var breedTypes = await _context.Breed
               .Select(b => new SelectListItem() { Text = b.BreedName, Value = b.BreedId.ToString() })
               .ToListAsync();
            var speciesTypes = await _context.Species
                .Select(s => new SelectListItem() { Text = s.SpeciesType, Value = s.SpeciesId.ToString() })
                .ToListAsync();
            var sexTypes = await _context.Sex
               .Select(s => new SelectListItem() { Text = s.SexType, Value = s.SexId.ToString() })
               .ToListAsync();
            var viewmodel = new PetDetailViewModel();
            viewmodel.SpeciesTypeOptions = speciesTypes;
            viewmodel.BreedTypeOptions = breedTypes;
            viewmodel.SexTypeOptions = sexTypes;
            return View(viewmodel);

        }

        // POST: Pets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PetDetailViewModel petDetailViewModel)
        {
            try
            {
                var user = await GetCurrentUserAsync();


                var pet = new Pet
                {
                    UserId = user.Id,
                    Name = petDetailViewModel.Pet.Name,
                    Birthday = petDetailViewModel.Pet.Birthday,
                    Color = petDetailViewModel.Pet.Color,
                    SpeciesId = petDetailViewModel.Pet.SpeciesId,
                    BreedId = petDetailViewModel.Pet.BreedId,
                    SexId = petDetailViewModel.Pet.SexId,
                    OngoingProblems = petDetailViewModel.Pet.OngoingProblems,
                    CurrentMedications = petDetailViewModel.Pet.CurrentMedications,
                    IsSpayedOrNeutered = petDetailViewModel.Pet.IsSpayedOrNeutered,
                };



                var uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images");
                if (petDetailViewModel.ImageFile != null)
                {
                    var fileName = Guid.NewGuid().ToString() + petDetailViewModel.ImageFile.FileName;
                    pet.ImagePath = fileName;
                    using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName), FileMode.Create))
                    {
                        await petDetailViewModel.ImageFile.CopyToAsync(fileStream);
                    }
                }


                pet.UserId = user.Id;
                _context.Pet.Add(pet);
                await _context.SaveChangesAsync();

             

                ViewData["petCreated"] = ("Your Pet has been Created.");
                ViewData["petId"] = pet;
                

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(nameof(Index));
            }
        }

        // GET: Pets/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var pet = await _context.Pet
               .Include(p => p.Breed)
               .Include(p => p.Sex)
               .Include(p => p.Species)
               .Include(p => p.Notes)
               .FirstOrDefaultAsync(p => p.PetId == id);

            var viewModel = new PetDetailViewModel()
            {
                Pet = new Pet()
            };

            viewModel.Pet.PetId = pet.PetId;
            viewModel.Pet.UserId = pet.UserId;
            viewModel.Pet.Name = pet.Name;
            viewModel.Pet.Color = pet.Color;
            viewModel.Pet.ImagePath = pet.ImagePath;
            viewModel.Pet.Birthday = pet.Birthday;
            viewModel.Pet.BreedId = pet.BreedId;
            viewModel.Pet.SexId = pet.SexId;
            viewModel.Pet.SpeciesId = pet.SpeciesId;
            viewModel.Pet.CurrentMedications = pet.CurrentMedications;
            viewModel.Pet.OngoingProblems = pet.OngoingProblems;
            viewModel.Pet.IsSpayedOrNeutered = pet.IsSpayedOrNeutered;
           

            var breedTypes = await _context.Breed
               .Select(b => new SelectListItem() { Text = b.BreedName, Value = b.BreedId.ToString() })
               .ToListAsync();
            var speciesTypes = await _context.Species
                .Select(s => new SelectListItem() { Text = s.SpeciesType, Value = s.SpeciesId.ToString() })
                .ToListAsync();
            var sexTypes = await _context.Sex
               .Select(s => new SelectListItem() { Text = s.SexType, Value = s.SexId.ToString() })
               .ToListAsync();
           
            viewModel.SpeciesTypeOptions = speciesTypes;
            viewModel.BreedTypeOptions = breedTypes;
            viewModel.SexTypeOptions = sexTypes;
            



            return View(viewModel);
        }

        // POST: Pets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, PetDetailViewModel petDetailViewModel)
        {
            try
            {
                var editPet = await _context.Pet
                    .FirstOrDefaultAsync(p => p.PetId == id);
                editPet.Name = petDetailViewModel.Pet.Name;
                editPet.Birthday = petDetailViewModel.Pet.Birthday;
                editPet.Color = petDetailViewModel.Pet.Color;
                editPet.OngoingProblems = petDetailViewModel.Pet.OngoingProblems;
                editPet.CurrentMedications = petDetailViewModel.Pet.CurrentMedications;
                editPet.IsSpayedOrNeutered = petDetailViewModel.Pet.IsSpayedOrNeutered;

BluegrassPetCare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bluegrass PetCare</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-solar.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
            <div class="container">
               
                <span class="navLogo">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/assets/petcare.png" />
                    </a>
                </span>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item active">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item active">
                                <a class="nav-link text-light" asp-area="" asp-controller="Pets" asp-action="Index">Pets</a>
                            </li>

                            @if (UserManager.GetUserAsync(User).Result.IsVeterinarian == true)
                            {

                                <li class="nav-item active">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Species" asp-action="Index">Species</a>
                                </li>
                            }

                            <li class="nav-item active">
                                <a class="nav-link text-light" asp-area="" asp-controller="Notes" asp-action="Index">Pet Notes</a>
                            </li>



                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;
            - Bluegrass PetCare - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>